version: '3.8'
services:  
  api:    
    build: ./index    
    container_name: server_for_game    
    ports:      
      - '80:80'    
    volumes:     
      - ./index      
      - ./node_modules